apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: demo-service
  template:
    metadata:
      labels:
        app: demo-service
    spec:
      containers:
        - name: demo-service
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
